In [1]:
# Import necessary libraries and modules
import pandas as pd
import pandapower as pp
import pandapower.networks as pn

from simulation_interface import GridSimulation
from typing import List
from pandapower import pandapowerNet
from sim_config import GridConfig, DataCenterConfig
from grid_regions import GridRegion
from grid_observer import plot_data
from datetime import datetime, timedelta
from generation_types import GenerationType

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [2]:
# Define the grid configuration and data center configuration for the simulation
ca_on_energy_profile = {
    GenerationType.SOLAR: 0.05,
    GenerationType.WIND: 0.08,
    GenerationType.HYDRO_RIVER: 0.24,
    GenerationType.NUCLEAR: 0.55,
    GenerationType.GAS: 0.8,
    GenerationType.BIOMASS: 0.008,
    GenerationType.OIL: 0.001,
}
energy_profile_share_descending = dict(sorted(ca_on_energy_profile.items(), key=lambda x: x[1], reverse=True))

grid_config = GridConfig(
        pp_grid = pn.case300(), # type: ignore
        region = GridRegion.CA_ON,
        energy_profile = energy_profile_share_descending
    )
data_center_config = DataCenterConfig(
    load_share = 0.5, 
    onsite_overprovision_factor = 1.0,
    onsite_generation_source = GenerationType.SOLAR,
)
load_id = grid_config.add_data_center(data_center_config)

# Initialize the grid simulation interface with the defined configurations
sim_interface = GridSimulation(
    grid_configs=[grid_config],
    shifting_threshold=10.0,
    enable_weather_variation=False
)

In [ ]:
# Verifies data center energy usage trend as load increases
start_date = pd.Timestamp("2024-01-01 00:00:00")
new_shares = [0.1 + 0.002 * i for i in range(400)]
SIMULATION_START_TIME: datetime = datetime.strptime('2020-08-01 00:00:00', '%Y-%m-%d %H:%M:%S')
current_time = SIMULATION_START_TIME

for share in new_shares:
    sim_interface.run_power_flow(date = current_time, observe = True)
    # sim_interface.update_dc_load_share("CA_ON", [load_id], [share])
    current_time += timedelta(hours = 1)

plot_data(
    x_data = new_shares,
    y_data = sim_interface.observer._ci_data,
    labels = sim_interface.observer._grid_names,
    x_label = "Data Center Load Share",
    y_label = "Grid Carbon Intensity (gCO2/kWh)",
    title = "Impact of Data Center Load Share on Grid Carbon Intensity"
)

SyntaxError: invalid syntax (4058136811.py, line 10)

In [ ]:
grid = sim_interface._grids[0]
energy_profile = grid.get_energy_profile()
for gen_type, share in energy_profile.items():
    print(f"{gen_type.value}: {share:.2%}")

solar: 0.00%
solar_non_varying: 0.00%
wind: 0.00%
wind_non_varying: 0.00%
coal: 0.00%
biomass: 0.00%
gas: 0.00%
oil: 0.00%
hydro_river: 0.00%
nuclear: 0.00%

In [ ]:
display(sim_interface._grids[0]._net.res_ext_grid)

           p_mw  q_mvar
0 -9.527033e-10     NaN

In [ ]:
display(sim_interface._grids[0]._net.res_gen)

            p_mw  q_mvar  va_degree  vm_pu
0   1.000000e+02     NaN  24.738501    1.0
1   1.167143e-09     NaN  25.320349    1.0
2   1.167143e-09     NaN  19.966375    1.0
3   1.167143e-09     NaN  -4.848584    1.0
4   1.167143e-09     NaN -14.354720    1.0
5   3.925915e+02     NaN  -4.661780    1.0
6   1.136609e-09     NaN  -2.295790    1.0
7   3.079369e+02     NaN   6.362817    1.0
8   1.598755e-08     NaN  -9.185471    1.0
9   1.136609e-09     NaN -12.950545    1.0
10  1.958059e+03     NaN  26.694855    1.0
11  2.603846e+02     NaN  11.560378    1.0
12  1.167143e-09     NaN   7.620688    1.0
13  1.167143e-09     NaN  10.290001    1.0
14  2.992782e+02     NaN  12.804696    1.0
15  7.288422e+02     NaN   8.381534    1.0
16  1.136609e-09     NaN   8.491940    1.0
17  1.136609e-09     NaN   8.867554    1.0
18  1.136609e-09     NaN   7.621219    1.0
19  3.894524e+02     NaN  24.071526    1.0
20  1.136609e-09     NaN  19.521294    1.0
21  1.167143e-09     NaN  20.020091    1.0
22  1.136609e-09     NaN  19.731529    1.0
23  1.167143e-09     NaN  12.759523    1.0
24  2.491921e+02     NaN  16.668056    1.0
25  1.598755e-08     NaN  10.365988    1.0
26  1.136609e-09     NaN   7.201522    1.0
27  1.234484e+03     NaN  19.888347    1.0
28  1.234484e+03     NaN  19.024627    1.0
29  4.970480e+02     NaN -11.793513    1.0
30  1.999961e+03     NaN  21.862636    1.0
31  4.432347e+02     NaN -11.638582    1.0
32  2.907563e+02     NaN -14.890633    1.0
33  1.136609e-09     NaN -12.605479    1.0
34  4.705755e+02     NaN -12.482735    1.0
35  2.698851e+02     NaN -12.550807    1.0
36  3.207427e+02     NaN -13.087917    1.0
37  3.623113e+02     NaN -10.858328    1.0
38  3.178157e+02     NaN -12.951635    1.0
39  6.298773e+02     NaN -11.667247    1.0
40  2.698845e+02     NaN -11.818440    1.0
41  5.769709e+02     NaN -11.284324    1.0
42  6.039650e+02     NaN -11.853062    1.0
43  1.136609e-09     NaN -16.952068    1.0
44  1.598755e-08     NaN -19.028086    1.0
45  4.884139e+02     NaN  31.416627    1.0
46  6.537979e+02     NaN  29.212628    1.0
47  1.244630e+03     NaN  28.964420    1.0
48  2.547755e+02     NaN  25.701201    1.0
49  3.894532e+02     NaN  26.404933    1.0
50  3.471798e+02     NaN  13.552455    1.0
51  1.136609e-09     NaN  22.485885    1.0
52  4.285399e+02     NaN  23.786333    1.0
53  5.234675e+02     NaN   6.957134    1.0
54  1.370000e+02     NaN  -1.060044    1.0
55  1.450000e+02     NaN   3.243109    1.0
56  1.136609e-09     NaN  -0.613032    1.0
57  4.181649e+02     NaN   7.862938    1.0
58  4.181659e+02     NaN   8.441831    1.0
59  1.136609e-09     NaN -20.670669    1.0
60  1.327928e+03     NaN  27.212896    1.0
61  7.329107e+02     NaN  11.629062    1.0
62  5.800123e+02     NaN  42.594678    1.0
63  1.167143e-09     NaN  -0.479650    1.0
64  1.167143e-09     NaN   0.959634    1.0
65  1.167143e-09     NaN   1.128823    1.0
66  1.598755e-08     NaN   1.754196    1.0
67  1.080000e+02     NaN   6.868286    1.0
68  1.192382e+04     NaN  31.392145    1.0
69  1.372695e-11     NaN  -1.060044    1.0
70  1.372695e-11     NaN   3.243109    1.0
71  1.372695e-11     NaN  -8.398760    1.0

In [ ]:
display(sim_interface._grids[0]._net.ext_grid)

,name,bus,vm_pu,va_degree,slack_weight,in_service,max_p_mw,min_p_mw,max_q_mvar,min_q_mvar,controllable,p_mw,source_type
0,None,256,1.0507,0.0,1.0,True,0.0,-inf,10.0,0.0,True,0.0,coal

In [ ]:
display(sim_interface._grids[0]._net.gen)

,name,bus,p_mw,vm_pu,sn_mva,min_q_mvar,max_q_mvar,scaling,slack,in_service,slack_weight,type,controllable,max_p_mw,min_p_mw,id_q_capability_characteristic,reactive_capability_curve,curve_style,power_limit,source_type,is_onsite_gen,is_backup_gen
0,None,7,0.0,1.0153,NaN,-10.00,10.00,1.0,False,True,0.0,None,True,100.000,0.0,<NA>,False,None,100.000,oil,False,False
1,None,9,0.0,1.0205,NaN,-20.00,20.00,1.0,False,True,0.0,None,True,100.000,0.0,<NA>,False,None,100.000,coal,False,False
2,None,18,0.0,1.0010,NaN,-20.00,20.00,1.0,False,True,0.0,None,True,100.000,0.0,<NA>,False,None,100.000,coal,False,False
3,None,54,0.0,0.9583,NaN,-25.00,25.00,1.0,False,True,0.0,None,True,100.000,0.0,<NA>,False,None,100.000,coal,False,False
4,None,62,0.0,0.9632,NaN,12.00,35.00,1.0,False,True,0.0,None,True,100.000,0.0,<NA>,False,None,100.000,coal,False,False
5,None,68,0.0,1.0250,NaN,-240.00,240.00,1.0,False,True,0.0,None,True,475.000,0.0,<NA>,False,None,475.000,gas,False,False
6,None,75,0.0,1.0520,NaN,-11.00,96.00,1.0,False,True,0.0,None,True,255.000,0.0,<NA>,False,None,255.000,nuclear,False,False
7,None,76,0.0,1.0520,NaN,-153.00,153.00,1.0,False,True,0.0,None,True,390.000,0.0,<NA>,False,None,390.000,gas,False,False
8,None,79,0.0,1.0000,NaN,-30.00,56.00,1.0,False,True,0.0,None,True,168.000,0.0,<NA>,False,None,168.000,hydro_river,False,False
9,None,87,0.0,0.9900,NaN,-24.00,77.00,1.0,False,True,0.0,None,True,217.000,0.0,<NA>,False,None,217.000,nuclear,False,False
10,None,97,0.0,1.0435,NaN,-500.00,1500.00,1.0,False,True,0.0,None,True,2030.000,0.0,<NA>,False,None,2030.000,gas,False,False
11,None,102,0.0,1.0233,NaN,-60.00,120.00,1.0,False,True,0.0,None,True,340.000,0.0,<NA>,False,None,340.000,gas,False,False
12,None,103,0.0,1.0103,NaN,-25.00,200.00,1.0,False,True,0.0,None,True,100.000,0.0,<NA>,False,None,100.000,coal,False,False
13,None,116,0.0,1.0550,NaN,-125.00,350.00,1.0,False,True,0.0,None,True,100.000,0.0,<NA>,False,None,100.000,coal,False,False
14,None,119,0.0,1.0510,NaN,-50.00,75.00,1.0,False,True,0.0,None,True,381.000,0.0,<NA>,False,None,381.000,gas,False,False
15,None,121,0.0,1.0435,NaN,-100.00,300.00,1.0,False,True,0.0,None,True,796.000,0.0,<NA>,False,None,796.000,gas,False,False
16,None,124,0.0,1.0528,NaN,-15.00,35.00,1.0,False,True,0.0,None,True,184.000,0.0,<NA>,False,None,184.000,nuclear,False,False
17,None,125,0.0,1.0528,NaN,-50.00,100.00,1.0,False,True,0.0,None,True,317.000,0.0,<NA>,False,None,317.000,nuclear,False,False
18,None,127,0.0,1.0735,NaN,-25.00,50.00,1.0,False,True,0.0,None,True,203.000,0.0,<NA>,False,None,203.000,nuclear,False,False
19,None,130,0.0,1.0535,NaN,-50.00,175.00,1.0,False,True,0.0,None,True,472.000,0.0,<NA>,False,None,472.000,gas,False,False
20,None,131,0.0,1.0435,NaN,-50.00,90.00,1.0,False,True,0.0,None,True,316.000,0.0,<NA>,False,None,316.000,nuclear,False,False
21,None,134,0.0,0.9630,NaN,-10.00,15.00,1.0,False,True,0.0,None,True,100.000,0.0,<NA>,False,None,100.000,coal,False,False
22,None,148,0.0,0.9290,NaN,-40.00,90.00,1.0,False,True,0.0,None,True,305.000,0.0,<NA>,False,None,305.000,nuclear,False,False
23,None,149,0.0,0.9829,NaN,-50.00,150.00,1.0,False,True,0.0,None,True,100.000,0.0,<NA>,False,None,100.000,coal,False,False
24,None,154,0.0,1.0522,NaN,-45.00,90.00,1.0,False,True,0.0,None,True,328.000,0.0,<NA>,False,None,328.000,gas,False,False
25,None,155,0.0,1.0077,NaN,-15.00,35.00,1.0,False,True,0.0,None,True,184.000,0.0,<NA>,False,None,184.000,hydro_river,False,False
26,None,163,0.0,1.0522,NaN,-50.00,80.00,1.0,False,True,0.0,None,True,300.000,0.0,<NA>,False,None,300.000,nuclear,False,False
27,None,164,0.0,1.0650,NaN,-100.00,400.00,1.0,False,True,0.0,None,True,1300.000,0.0,<NA>,False,None,1300.000,gas,False,False
28,None,165,0.0,1.0650,NaN,-100.00,400.00,1.0,False,True,0.0,None,True,1300.000,0.0,<NA>,False,None,1300.000,gas,False,False
29,None,168,0.0,1.0551,NaN,-300.00,300.00,1.0,False,True,0.0,None,True,575.000,0.0,<NA>,False,None,575.000,gas,False,False
30,None,169,0.0,1.0435,NaN,-1000.00,1000.00,1.0,False,True,0.0,None,True,2073.000,0.0,<NA>,False,None,2073.000,gas,False,False
31,None,176,0.0,1.0150,NaN,-260.00,260.00,1.0,False,True,0.0,None,True,524.000,0.0,<NA>,False,None,524.000,gas,False,False
32,None,191,0.0,1.0100,NaN,-150.00,150.00,1.0,False,True,0.0,None,True,372.000,0.0,<NA>,False,None,372.000,gas,False,False
33,None,198,0.0,1.0080,NaN,-60.00,60.00,1.0,False,True,0.0,None,True,200.000,0.0,<NA>,False,None,200.000,nuclear,False,False
34,None,199,0.0,1.0000,NaN,-320.00,320.00,1.0,False,True,0.0,None,True,550.000,0.0,<NA>,False,None,550.000,gas,False,False
35,None,200,0.0,1.0500,NaN,-300.00,300.00,1.0,False,True,0.0,None,True,350.000,0.0,<NA>,False,None,350.000,gas,False,False
36,None,205,0.0,1.0000,NaN,-300.00,300.00,1.0,False,True,0.0,None,True,403.000,0.0,<NA>,False,None,403.000,gas,False,False
37,None,208,0.0,1.0400,NaN,-250.00,250.00,1.0,False,True,0.0,None,True,445.000,0.0,<NA>,False,None,445.000,gas,False,False
38,None,211,0.0,1.0000,NaN,-500.00,500.00,1.0,False,True,0.0,None,True,400.000,0.0,<NA>,False,None,400.000,gas,False,False
39,None,214,0.0,1.0165,NaN,-300.00,300.00,1.0,False,True,0.0,None,True,700.000,0.0,<NA>,False,None,700.000,gas,False,False
40,None,216,0.0,1.0100,NaN,-200.00,200.00,1.0,False,True,0.0,None,True,350.000,0.0,<NA>,False,None,350.000,gas,False,False
41,None,217,0.0,1.0000,NaN,-400.00,400.00,1.0,False,True,0.0,None,True,650.000,0.0,<NA>,False,None,650.000,gas,False,False
42,None,219,0.0,1.0500,NaN,-600.00,600.00,1.0,False,True,0.0,None,True,675.430,0.0,<NA>,False,None,675.430,gas,False,False
43,None,220,0.0,0.9930,NaN,40.00,100.00,1.0,False,True,0.0,None,True,270.000,0.0,<NA>,False,None,270.000,nuclear,False,False
44,None,221,0.0,1.0100,NaN,40.00,80.00,1.0,False,True,0.0,None,True,184.000,0.0,<NA>,False,None,184.000,hydro_river,False,False
45,None,246,0.0,1.0507,NaN,-210.00,210.00,1.0,False,True,0.0,None,True,567.000,0.0,<NA>,False,None,567.000,gas,False,False
46,None,247,0.0,1.0507,NaN,-280.00,280.00,1.0,False,True,0.0,None,True,723.000,0.0,<NA>,False,None,723.000,gas,False,False
47,None,248,0.0,1.0323,NaN,-420.00,420.00,1.0,False,True,0.0,None,True,1310.000,0.0,<NA>,False,None,1310.000,gas,False,False
48,None,249,0.0,1.0145,NaN,-100.00,100.00,1.0,False,True,0.0,None,True,334.000,0.0,<NA>,False,None,334.000,gas,False,False
49,None,250,0.0,1.0507,NaN,-224.00,224.00,1.0,False,True,0.0,None,True,472.000,0.0,<NA>,False,None,472.000,gas,False,False
50,None,251,0.0,1.0507,NaN,0.00,350.00,1.0,False,True,0.0,None,True,430.000,0.0,<NA>,False,None,430.000,gas,False,False
51,None,252,0.0,1.0507,NaN,0.00,120.00,1.0,False,True,0.0,None,True,285.000,0.0,<NA>,False,None,285.000,nuclear,False,False
52,None,253,0.0,1.0290,NaN,-224.00,224.00,1.0,False,True,0.0,None,True,510.000,0.0,<NA>,False,None,510.000,gas,False,False
53,None,254,0.0,1.0500,NaN,-200.00,200.00,1.0,False,True,0.0,None,True,600.000,0.0,<NA>,False,None,600.000,gas,False,False
54,None,255,0.0,1.0145,NaN,0.00,42.00,1.0,False,True,0.0,None,True,137.000,0.0,<NA>,False,None,137.000,wind,False,False
55,None,257,0.0,0.9967,NaN,0.00,25.00,1.0,False,True,0.0,None,True,145.000,0.0,<NA>,False,None,145.000,wind,False,False
56,None,258,0.0,1.0212,NaN,-90.00,90.00,1.0,False,True,0.0,None,True,265.000,0.0,<NA>,False,None,265.000,nuclear,False,False
57,None,259,0.0,1.0145,NaN,-150.00,150.00,1.0,False,True,0.0,None,True,500.000,0.0,<NA>,False,None,500.000,gas,False,False
58,None,260,0.0,1.0017,NaN,0.00,150.00,1.0,False,True,0.0,None,True,500.000,0.0,<NA>,False,None,500.000,gas,False,False
59,None,261,0.0,0.9893,NaN,0.00,87.00,1.0,False,True,0.0,None,True,216.000,0.0,<NA>,False,None,216.000,nuclear,False,False
60,None,262,0.0,1.0507,NaN,-100.00,600.00,1.0,False,True,0.0,None,True,1392.000,0.0,<NA>,False,None,1392.000,gas,False,False
61,None,263,0.0,1.0507,NaN,-125.00,325.00,1.0,False,True,0.0,None,True,800.000,0.0,<NA>,False,None,800.000,gas,False,False
62,None,264,0.0,1.0145,NaN,-200.00,300.00,1.0,False,True,0.0,None,True,653.000,0.0,<NA>,False,None,653.000,gas,False,False
63,None,266,0.0,0.9945,NaN,-2.00,2.00,1.0,False,True,0.0,None,True,100.000,0.0,<NA>,False,None,100.000,coal,False,False
64,None,291,0.0,1.0000,NaN,-17.35,17.35,1.0,False,True,0.0,None,True,100.000,0.0,<NA>,False,None,100.000,coal,False,False
65,None,293,0.0,1.0000,NaN,-12.80,12.83,1.0,False,True,0.0,None,True,100.000,0.0,<NA>,False,None,100.000,coal,False,False
66,None,294,0.0,1.0000,NaN,-38.00,38.00,1.0,False,True,0.0,None,True,150.000,0.0,<NA>,False,None,150.000,hydro_river,False,False
67,None,295,0.0,1.0000,NaN,-6.00,6.00,1.0,False,True,0.0,None,True,108.000,0.0,<NA>,False,None,108.000,biomass,False,False
68,None,300,0.0,1.0000,NaN,NaN,NaN,1.0,False,True,0.0,None,True,11923.825,0.0,<NA>,False,NaN,11923.825,solar,True,False
69,None,301,0.0,1.0000,NaN,NaN,NaN,1.0,False,True,0.0,None,True,137.000,0.0,<NA>,False,NaN,137.000,wind_non_varying,False,True
70,None,302,0.0,1.0000,NaN,NaN,NaN,1.0,False,True,0.0,None,True,145.000,0.0,<NA>,False,NaN,145.000,wind_non_varying,False,True
71,None,303,0.0,1.0000,NaN,NaN,NaN,1.0,False,True,0.0,None,True,113.700,0.0,<NA>,False,NaN,113.700,solar_non_varying,False,True

In [ ]:
display(sim_interface._grids[0]._net.sgen)

,name,bus,p_mw,q_mvar,sn_mva,scaling,in_service,type,current_source,controllable,id_q_capability_characteristic,reactive_capability_curve,curve_style,min_p_mw,max_p_mw,power_limit,source_type,is_onsite_gen,is_backup_gen
0,None,43,0.0,-5.00,NaN,1.0,True,,True,True,<NA>,False,None,0.0,5.0,5.0,coal,False,False
1,None,185,0.0,14.20,NaN,1.0,True,,True,True,<NA>,False,None,0.0,21.0,21.0,coal,False,False
2,None,228,0.0,17.00,NaN,1.0,True,,True,True,<NA>,False,None,0.0,23.0,23.0,coal,False,False
3,None,229,0.0,29.40,NaN,1.0,True,,True,True,<NA>,False,None,0.0,33.1,33.1,coal,False,False
4,None,233,0.0,-26.50,NaN,1.0,True,,True,True,<NA>,False,None,0.0,14.9,14.9,coal,False,False
5,None,238,0.0,1.40,NaN,1.0,True,,True,True,<NA>,False,None,0.0,11.1,11.1,coal,False,False
6,None,241,0.0,-76.70,NaN,1.0,True,,True,True,<NA>,False,None,0.0,113.7,113.7,solar,False,False
7,None,243,0.0,-34.17,NaN,1.0,True,,True,True,<NA>,False,None,0.0,100.0,100.0,coal,False,False

In [ ]:
display(sim_interface._grids[0]._net.load)

,name,bus,p_mw,q_mvar,const_z_p_percent,const_z_q_percent,const_i_p_percent,const_i_q_percent,sn_mva,scaling,in_service,type,controllable,is_data_center,power_limit
0,None,0,10707.59485,49.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,True,11923.825
1,None,1,56.00000,15.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
2,None,2,20.00000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
3,None,4,353.00000,130.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
4,None,5,120.00000,41.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
5,None,7,63.00000,14.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
6,None,8,96.00000,43.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
7,None,9,153.00000,33.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
8,None,10,83.00000,21.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
9,None,12,58.00000,10.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
10,None,13,160.00000,60.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
11,None,14,126.70000,23.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
12,None,16,561.00000,220.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
13,None,18,605.00000,120.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
14,None,19,77.00000,1.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
15,None,20,81.00000,23.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
16,None,21,21.00000,7.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
17,None,23,45.00000,12.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
18,None,24,28.00000,9.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
19,None,25,69.00000,13.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
20,None,26,55.00000,6.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
21,None,30,85.00000,32.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
22,None,31,155.00000,18.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
23,None,33,46.00000,-21.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
24,None,34,86.00000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
25,None,36,39.00000,9.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
26,None,37,195.00000,29.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
27,None,40,58.00000,11.80,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
28,None,41,41.00000,19.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
29,None,42,92.00000,26.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
30,None,44,61.00000,28.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
31,None,45,69.00000,3.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
32,None,46,10.00000,1.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
33,None,47,22.00000,10.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
34,None,48,98.00000,20.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
35,None,49,14.00000,1.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
36,None,50,218.00000,106.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
37,None,52,227.00000,110.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
38,None,54,70.00000,30.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
39,None,57,56.00000,20.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
40,None,58,116.00000,38.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
41,None,59,57.00000,19.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
42,None,60,224.00000,71.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
43,None,62,208.00000,107.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
44,None,63,74.00000,28.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
45,None,65,48.00000,14.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
46,None,66,28.00000,7.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
47,None,68,37.00000,13.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
48,None,73,44.20000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
49,None,74,66.00000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
50,None,75,17.40000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
51,None,76,15.80000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
52,None,77,60.30000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
53,None,78,39.90000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
54,None,79,66.70000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
55,None,80,83.50000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
56,None,82,77.80000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
57,None,83,32.00000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
58,None,84,8.60000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
59,None,85,49.60000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
60,None,86,4.60000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
61,None,87,112.10000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
62,None,88,30.70000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
63,None,89,63.00000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
64,None,90,19.60000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
65,None,91,26.20000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
66,None,92,18.20000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
67,None,96,14.10000,650.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
68,None,98,777.00000,215.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
69,None,99,535.00000,55.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
70,None,100,229.10000,11.80,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
71,None,101,78.00000,1.40,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
72,None,102,276.40000,59.30,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
73,None,103,514.80000,82.70,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
74,None,104,57.90000,5.10,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
75,None,105,380.80000,37.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
76,None,113,169.20000,41.60,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
77,None,114,55.20000,18.20,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
78,None,115,273.60000,99.80,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
79,None,116,1019.20000,135.20,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
80,None,117,595.00000,83.30,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
81,None,118,387.70000,114.70,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
82,None,119,145.00000,58.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
83,None,120,56.50000,24.50,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
84,None,121,89.50000,35.50,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
85,None,123,24.00000,14.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
86,None,126,63.00000,25.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
87,None,130,17.00000,9.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
88,None,132,70.00000,5.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
89,None,133,200.00000,50.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
90,None,134,75.00000,50.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
91,None,135,123.50000,-24.30,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
92,None,137,33.00000,16.50,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
93,None,139,35.00000,15.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
94,None,140,85.00000,24.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
95,None,141,0.00000,0.40,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
96,None,145,299.90000,95.70,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
97,None,148,481.80000,205.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
98,None,149,763.60000,291.10,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
99,None,150,26.50000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
100,None,151,163.50000,43.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
101,None,153,176.00000,83.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
102,None,154,5.00000,4.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
103,None,155,28.00000,12.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
104,None,156,427.40000,173.60,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
105,None,157,74.00000,29.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
106,None,158,69.50000,49.30,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
107,None,159,73.40000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
108,None,160,240.70000,89.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
109,None,161,40.00000,4.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
110,None,162,136.80000,16.60,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
111,None,164,59.80000,24.30,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
112,None,165,59.80000,24.30,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
113,None,166,182.60000,43.60,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
114,None,167,7.00000,2.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
115,None,169,489.00000,53.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
116,None,170,800.00000,72.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
117,None,174,10.00000,3.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
118,None,175,43.00000,14.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
119,None,176,64.00000,21.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
120,None,177,35.00000,12.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
121,None,178,27.00000,12.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
122,None,179,41.00000,14.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
123,None,180,38.00000,13.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
124,None,181,42.00000,14.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
125,None,182,72.00000,24.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
126,None,183,0.00000,-5.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
127,None,184,12.00000,2.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
128,None,186,7.00000,2.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
129,None,187,38.00000,13.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
130,None,189,96.00000,7.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
131,None,192,22.00000,16.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
132,None,193,47.00000,26.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
133,None,194,176.00000,105.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
134,None,195,100.00000,75.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
135,None,196,131.00000,96.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
136,None,198,285.00000,100.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
137,None,199,171.00000,70.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
138,None,200,328.00000,188.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
139,None,201,428.00000,232.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
140,None,202,173.00000,99.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
141,None,203,410.00000,40.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
142,None,205,538.00000,369.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
143,None,206,223.00000,148.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
144,None,207,96.00000,46.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
145,None,209,159.00000,107.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
146,None,210,448.00000,143.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
147,None,211,404.00000,212.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
148,None,212,572.00000,244.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
149,None,213,269.00000,157.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
150,None,216,255.00000,149.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
151,None,221,8.00000,3.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
152,None,223,61.00000,30.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
153,None,224,77.00000,33.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
154,None,225,61.00000,30.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
155,None,226,29.00000,14.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
156,None,227,29.00000,14.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
157,None,230,115.80000,-24.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
158,None,231,2.40000,-12.60,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
159,None,232,2.40000,-3.90,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
160,None,234,24.70000,-1.20,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
161,None,235,145.30000,-34.90,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
162,None,236,28.10000,-20.50,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
163,None,237,14.00000,2.50,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
164,None,239,50.50000,17.40,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
165,None,240,29.60000,0.60,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
166,None,242,100.31000,29.17,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
167,None,266,4.20000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
168,None,267,2.71000,0.94,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
169,None,268,0.86000,0.28,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
170,None,273,4.75000,1.56,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
171,None,274,1.53000,0.53,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
172,None,276,1.35000,0.47,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
173,None,277,0.45000,0.16,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
174,None,278,0.45000,0.16,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
175,None,279,1.84000,0.64,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
176,None,280,1.39000,0.48,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
177,None,281,1.89000,0.65,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
178,None,282,1.55000,0.54,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
179,None,283,1.66000,0.58,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
180,None,284,3.03000,1.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
181,None,285,1.86000,0.64,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
182,None,286,2.58000,0.89,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
183,None,287,1.01000,0.35,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
184,None,288,0.81000,0.28,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
185,None,289,1.60000,0.52,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
186,None,291,35.81000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
187,None,292,30.00000,23.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
188,None,293,26.48000,0.00,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
189,None,296,1.02000,0.35,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
190,None,297,1.02000,0.35,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
191,None,298,3.80000,1.25,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN
192,None,299,1.19000,0.41,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False,False,NaN

In [ ]:
display(sim_interface._grids[0]._net.poly_cost)

,element,et,cp0_eur,cp1_eur_per_mw,cp2_eur_per_mw2,cq0_eur,cq1_eur_per_mvar,cq2_eur_per_mvar2
0,0,gen,0.0,82.152381,0.0,0.0,0.0,0.0
1,1,gen,0.0,178.500000,0.0,0.0,0.0,0.0
2,10,gen,0.0,97.500000,0.0,0.0,0.0,0.0
3,11,gen,0.0,97.500000,0.0,0.0,0.0,0.0
4,12,gen,0.0,178.500000,0.0,0.0,0.0,0.0
5,13,gen,0.0,178.500000,0.0,0.0,0.0,0.0
6,14,gen,0.0,97.500000,0.0,0.0,0.0,0.0
7,15,gen,0.0,97.500000,0.0,0.0,0.0,0.0
8,16,gen,0.0,180.500000,0.0,0.0,0.0,0.0
9,17,gen,0.0,180.500000,0.0,0.0,0.0,0.0
10,18,gen,0.0,180.500000,0.0,0.0,0.0,0.0
11,19,gen,0.0,97.500000,0.0,0.0,0.0,0.0
12,2,gen,0.0,178.500000,0.0,0.0,0.0,0.0
13,20,gen,0.0,180.500000,0.0,0.0,0.0,0.0
14,21,gen,0.0,178.500000,0.0,0.0,0.0,0.0
15,22,gen,0.0,180.500000,0.0,0.0,0.0,0.0
16,23,gen,0.0,178.500000,0.0,0.0,0.0,0.0
17,24,gen,0.0,97.500000,0.0,0.0,0.0,0.0
18,25,gen,0.0,103.880000,0.0,0.0,0.0,0.0
19,26,gen,0.0,180.500000,0.0,0.0,0.0,0.0
20,27,gen,0.0,97.500000,0.0,0.0,0.0,0.0
21,28,gen,0.0,97.500000,0.0,0.0,0.0,0.0
22,29,gen,0.0,97.500000,0.0,0.0,0.0,0.0
23,3,gen,0.0,178.500000,0.0,0.0,0.0,0.0
24,30,gen,0.0,97.500000,0.0,0.0,0.0,0.0
25,31,gen,0.0,97.500000,0.0,0.0,0.0,0.0
26,32,gen,0.0,97.500000,0.0,0.0,0.0,0.0
27,33,gen,0.0,180.500000,0.0,0.0,0.0,0.0
28,34,gen,0.0,97.500000,0.0,0.0,0.0,0.0
29,35,gen,0.0,97.500000,0.0,0.0,0.0,0.0
30,36,gen,0.0,97.500000,0.0,0.0,0.0,0.0
31,37,gen,0.0,97.500000,0.0,0.0,0.0,0.0
32,38,gen,0.0,97.500000,0.0,0.0,0.0,0.0
33,39,gen,0.0,97.500000,0.0,0.0,0.0,0.0
34,4,gen,0.0,178.500000,0.0,0.0,0.0,0.0
35,40,gen,0.0,97.500000,0.0,0.0,0.0,0.0
36,41,gen,0.0,97.500000,0.0,0.0,0.0,0.0
37,42,gen,0.0,97.500000,0.0,0.0,0.0,0.0
38,43,gen,0.0,180.500000,0.0,0.0,0.0,0.0
39,44,gen,0.0,103.880000,0.0,0.0,0.0,0.0
40,45,gen,0.0,97.500000,0.0,0.0,0.0,0.0
41,46,gen,0.0,97.500000,0.0,0.0,0.0,0.0
42,47,gen,0.0,97.500000,0.0,0.0,0.0,0.0
43,48,gen,0.0,97.500000,0.0,0.0,0.0,0.0
44,49,gen,0.0,97.500000,0.0,0.0,0.0,0.0
45,5,gen,0.0,97.500000,0.0,0.0,0.0,0.0
46,50,gen,0.0,97.500000,0.0,0.0,0.0,0.0
47,51,gen,0.0,180.500000,0.0,0.0,0.0,0.0
48,52,gen,0.0,97.500000,0.0,0.0,0.0,0.0
49,53,gen,0.0,97.500000,0.0,0.0,0.0,0.0
50,54,gen,0.0,0.000000,0.0,0.0,0.0,0.0
51,0,ext_grid,0.0,0.000000,0.0,0.0,0.0,0.0
52,55,gen,0.0,0.000000,0.0,0.0,0.0,0.0
53,56,gen,0.0,180.500000,0.0,0.0,0.0,0.0
54,57,gen,0.0,97.500000,0.0,0.0,0.0,0.0
55,58,gen,0.0,97.500000,0.0,0.0,0.0,0.0
56,6,gen,0.0,180.500000,0.0,0.0,0.0,0.0
57,59,gen,0.0,180.500000,0.0,0.0,0.0,0.0
58,60,gen,0.0,97.500000,0.0,0.0,0.0,0.0
59,61,gen,0.0,97.500000,0.0,0.0,0.0,0.0
60,62,gen,0.0,97.500000,0.0,0.0,0.0,0.0
61,63,gen,0.0,178.500000,0.0,0.0,0.0,0.0
62,64,gen,0.0,178.500000,0.0,0.0,0.0,0.0
63,65,gen,0.0,178.500000,0.0,0.0,0.0,0.0
64,66,gen,0.0,103.880000,0.0,0.0,0.0,0.0
65,67,gen,0.0,84.540000,0.0,0.0,0.0,0.0
66,7,gen,0.0,97.500000,0.0,0.0,0.0,0.0
67,8,gen,0.0,103.880000,0.0,0.0,0.0,0.0
68,9,gen,0.0,180.500000,0.0,0.0,0.0,0.0
69,0,sgen,0.0,178.500000,0.0,0.0,0.0,0.0
70,1,sgen,0.0,178.500000,0.0,0.0,0.0,0.0
71,2,sgen,0.0,178.500000,0.0,0.0,0.0,0.0
72,3,sgen,0.0,178.500000,0.0,0.0,0.0,0.0
73,4,sgen,0.0,178.500000,0.0,0.0,0.0,0.0
74,5,sgen,0.0,178.500000,0.0,0.0,0.0,0.0
75,6,sgen,0.0,90.500000,0.0,0.0,0.0,0.0
76,7,sgen,0.0,178.500000,0.0,0.0,0.0,0.0
77,68,gen,0.0,0.000000,0.0,0.0,0.0,0.0
78,69,gen,1000.0,1000.000000,0.0,0.0,0.0,0.0
79,70,gen,1000.0,1000.000000,0.0,0.0,0.0,0.0
80,71,gen,1000.0,1000.000000,0.0,0.0,0.0,0.0